NDefines.NMilitary.ARCHERS_MAINTENANCE = 1--2
NDefines.NMilitary.KNIGHTS_MAINTENANCE = 1--6
NDefines.NMilitary.LIGHT_CAVALRY_MAINTENANCE = 1--3
NDefines.NMilitary.PIKEMEN_MAINTENANCE = 1--2
NDefines.NMilitary.HEAVY_INFANTRY_MAINTENANCE = 1--3
NDefines.NMilitary.LIGHT_INFANTRY_MAINTENANCE = 1--0.70
NDefines.NTitle.MAX_CROWN_LAW_CHANGES = 99
NDefines.NTitle.ENFORCE_ONE_OF_EACH_HOLDING = 0